= Antora Content Management
:icons: font
:stem:

== Use Resources

.Antora Content Organization
|===
| Directory | Purpose
| attachments | resource, such as the ZIP archive, pdf of a sample project, that a site visitor can download via a link, using `link` macro
| partials | reusable content snippets such as product descriptions and definitions, using `include` directive
| images | using *image:name[]* macro
| examples | source code file, using `include`
|===

https://c4model.com/[How to diagram using C4 model ?]

=== Examples

[source, edn]
----
include::example$edn4.edn[optional attributes]
----

=== partials

include::partial$sample.adoc[]

=== Images

image::edn.svg[]

=== Attachments

like `pdf` and `zip` file for downloads

link:{attachmentsdir}/chart.pdf[Download the PDF example] and read it.

link:{attachmentsdir}/chart.html[view prebuilt HTML page]


== Use bytefield

.A byteframe
[bytefield]
----
(draw-column-headers)
(doseq [val (range 30)]
  (draw-box val))
----


.A byte field
[bytefield]
----
(draw-column-headers)
(draw-box 42 {:fill "orange"})
(draw-gap "Whee!" {:fill "yellow"})
(draw-bottom {:fill "#a0ffa0"})
----

And some more text.

[bytefield]
----
(draw-box 1)
(draw-box "two" {:span 2})
(draw-box nil {:fill "#a0ffa0"})
(draw-box false {:fill "lightgrey"})
----


## Tweet

tweet::104136996043670323[]

## emoji:pick[] LaTex

> Using maths on web?

. emoji:bomb[] Challenges with maths on web emoji:chains[]
* characters and layouts convey meaning
* screenreaders and *a11y*
* images and text, looses semantic meaning
* Multiple Languages implementations to solve this problem `TeX`, `LaTeX`, `MathML`

TIP: Use [green]#MathTypes# text language then process it with MathJax.
And then you can do something like https://mathjax.github.io/MathJax-demos-web/tex-chtml.html[this]


[stem]
++++
x = {-b \pm \sqrt{b^2-4ac} \over 2a}.
From A \rightarrow B
++++

Without stem

++++
x = {-b \pm \sqrt{b^2-4ac} \over 2a}.
\rightarrow
++++

A matrix can be written as

[stem]
++++
[[a,b],[c,d]]((n),(k))
sqrt(4) = 2
sqrt(9) = 3
++++


## Interactive

[source%interactive,javascript]
----
const {camelCase} = require('lodash');
console.log(camelCase('get content'));  <1>
----
<1> Now you can see the output of this line in the browser.

## Content Organization

color:#FF5733[]

[%hardbreaks]
`#fcf`
`#00BCD4`
`rgb(232, 74, 87)`
`rgba(103,58,183,50%)`
`hsl(88, 50%, 53%)`
`hsla(36, 100%, 50%, 75%)`

We should use the color color:blueviolet[] in our logo.


[stem]
++++
Extensions to asciidoc\tor.register()
++++

* Extensions are shared by all pages

[How can I use asciidoc extensions in antora?](https://gitlab.com/antora/antora/-/issues/442)

.Extensions
* https://asciidoctor-docs.netlify.app/asciidoctor.js/extend/extensions/ecosystem/


[plantuml,format=svg,role=sequence]
....
alice -> bob
....

[graphviz]
....
digraph foo {
  node [style=rounded]
  node1 [shape=box]
  node2 [fillcolor=yellow, style="rounded,filled", shape=diamond]
  node3 [shape=record, label="{ a | b | c }"]
   node1 -> node2 -> node3
}
....


WARNING: Features and issues

* [ ] emoji:white_check_mark[] Use LaTex with MathJax
* [ ] emoji:white_check_mark[] Use bytefield
* [ ] emoji:x[] Interactive code-block?
* [ ] emoji:x[] Color chips?

== Issues

=== emoji:beetle[] How to use asciidoc-charts?

* https://gionkunz.github.io/chartist-js/

Issue is to include chartist css and js on page `<  head>`

== AWS Architecture diagrams

[plantuml]
....
!include <aws/common>
!include <aws/Storage/AmazonS3/AmazonS3>
!include <aws/Storage/AmazonS3/bucket/bucket>
AMAZONS3(s3_internal)
AMAZONS3(s3_partner,"Vendor's S3")
s3_internal <- s3_partner
....

New diagram

[plantuml]
....
!include <aws/common>
!include <aws/Storage/AmazonS3/AmazonS3>
!include <aws/Storage/AmazonS3/bucket/bucket>
!include <aws/Compute/AWSLambda/AWSLambda>

!define AWS(e_text, e_as, e_service, e_image, e_size) AWSLAMBDA(e_as, e_text, node, #000000, e_service, "none><img:e_image{scale=e_size}> <$none")
!define AWS_Light(e_text, e_as, e_service, e_image, e_size) AWS(e_text, e_as, e_service, ./img/AWS-Architecture-Icons_PNG_20200430/PNG Light/e_image, e_size)
!define Alexa(e_text, e_as) AWS_Light(e_text, e_as, Alexa skill, Internet of Things/IoT_Alexa-skill_light-bg@4x.png, 0.3)
!define Lambda(e_text, e_as) AWS_Light(e_text, e_as, AWS Lambda, Compute/AWS-Lambda@4x.png, 0.3)
!define LambdaFunction(e_text, e_as) AWS_Light(e_text, e_as, Lambda Function, Compute/AWS-Lambda_Lambda-Function_light-bg@4x.png, 0.3)
!define Dynamo(e_text, e_as) AWS_Light(e_text, e_as, DynamoDB, Database/Amazon-DynamoDB@4x.png, 0.3)
!define Table(e_text, e_as) AWS_Light(e_text, e_as, DynamoDB Table, Database/Amazon-DynamoDB_Table_light-bg@4x.png, 0.3)

actor User as user
Alexa(OneCall Timer, onecall)
Lambda(Timer Lambda, timer)
LambdaFunction(Timer Receiver, receiver)
LambdaFunction(Timer Attacker, attacker)
Dynamo(User DB, user_db)
Table(user-table, user_table)

user - onecall
onecall - timer
timer - user_db

timer +-- receiver
timer +-- attacker

user_db +-- user_table
....

=== Mermaid

[mermaid,abcd-flowchart,svg]
....
graph TD;
A-->B;
A-->C;
B-->D;
C-->D;
....

