theme = "adwaita-dark"

# hard to tell when 2 suggestions which one is selected in code completion
# when grepping sometimes previews are un-viewable
# find references of get_usage the bar is blue the text is the same blue and I
# can't see what's going on
#
# symbol highlighting also not working, possibly a theme problem
#
# we cannot use any red for the text -- the diagnostics are shown in the top right and the clash is prohibitive
# theme = "base16_default"

[editor]
cursor-shape = { insert = "bar" }
cursorline = true
cursorcolumn = true
indent-guides = { render = true, skip-levels = 1 }

# status line desires
# git info
# lsp info
#
# ]d should prioritize errors 
#
# helix config lsp?
# toml auto formatter?

[keys.insert]
# would like to be able to scroll down and up with C-j C-k, tbd on whether cursor should move
C-e = "insert_at_line_end"

[keys.normal]
esc = ":write-all"
C-r = ":reload-all"
C-l = ":theme adwaita-light"
C-k = ":theme adwaita-dark"

[keys.normal."space"]
E = "@ D%p !tests %s ERROR"
