#!/usr/bin/env python
#
# Copyright 2012 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""A convenience wrapper for starting gcutil."""



import os
import platform
import shlex
import subprocess
import sys

# Checks the Python version.
if not hasattr(sys, 'version_info'):
  sys.stderr.write('Very old versions of Python are not supported. Please '
                   'use version 2.6 or greater.\n')
  sys.exit(1)
if tuple(sys.version_info[:2]) < (2, 6):
  sys.stderr.write('Python %d.%d is not supported. Please use version 2.6 '
                   'or greater.\n' % tuple(sys.version_info[:2]))
  sys.exit(1)


def main():
  """Launches gcutil using python -S.

  The -S ensures that the site module is not imported and eliminates a
  class of problems that can occur when the user's system has multiple
  versions of a library.
  """
  python_bin = sys.executable

  gcutil_main = os.path.join(
      os.path.dirname(os.path.realpath(__file__)),
      'lib',
      'google_compute_engine',
      'gcutil_lib',
      'gcutil')

  python_args = os.environ.get('CLOUDSDK_PYTHON_ARGS', '-S')
  args = [python_bin]

  posix = platform.system() != 'Windows'
  args.extend(shlex.split(python_args, posix=posix))

  args.append(gcutil_main)
  args.extend(sys.argv[1:])

  if platform.system() == 'Windows':
    subprocess.Popen(args).wait()
  else:
    os.execv(python_bin, args)


if __name__ == '__main__':
  main()
