= Architecture

== C4 Diagramming Model

[mermaid]
....
graph LR
A(Context):::blue
B(Container):::orange
C(Components):::purple
D(Code/Classes):::yellow
A --> B --> C --> D
classDef orange fill:#f96,stroke-width:0px;
classDef yellow fill:#FFE873,stroke-width:0px;
classDef blue fill:#b8d4ff,stroke-width:0px;
classDef purple fill:#f9f,stroke:#333,stroke-width:0px;
....

> 97 ways to sidestep UML

[quote]
____
Just use a whiteboard
____

* Google https://www.google.com/search?q=Software+architecture+diagrams[Software archotecture diagrams]
* If we have 2 different maps, they will represent the same information, irrespective of different color coding, legends, language used etc.
* CONTAINER - individual unit
  * Mobile App
  * web app
  * a script
* COMPONENTS - runs inside containers
* Structure - drill down into details
* Diagrams are Maps
* CONTEXT - Interaction between people and software system
* Containers, Component, Classes - interactions between various pieces of system
* Use single direcctional arrows only
* Read your diagrams outloud
* Different color codes for external and internal systems
* Solid lines for Synchronous calls
* Dashed lines for Asynchronous calls

> Make diagrams stand on their own

[plantuml]
....
include::example$c4.puml[]
....

[plantuml]
....
include::example$c4-2.puml[]
....

=== 2 Introduction to the Cambridge MQTT service

=== 2.1 Basic informations:

Projekt Cambridge zajmuje się speedcamami (Raporty na podstawie których tworzone są kamery)
Cambridge Mqtt to popdrojekt który ma zadanie dostarczać w czasie rzeczywistym informacje o kamerach
Cambridge Mqtt jest oparty o technologie MQTT oraz morton cody



Ogólnie w 2 zdaniach co ma robić - tj samochody będa w stanie odbierać informacje o


=== 2.2 Mqtt

Czym jest mqtt – 2 zdania że to kolejka I że można sie subskrybować na dany topic aby odbierać informacje o tym co tam jest I o zmianach.

Odnośnik do oficjalnuych dokumentów

=== 2.3 Morton code

Czym są morton cody - dzielą świat na kwadraty w zależności od poziomu

Czym są jak działają, jakie biblioteki wykorzystujemy

=== 2.4 Morton code and mqtt topics

Wyjaśnienie że same morton cody były wykorzystane aby móc nadawać nazwy topicom itp.

(Topic naming strategyreference to how_mqtt_works and tile partitioningshort description of topic structure)

=== 2.5 Cambridge Camera

Informacje o przykładowej kamerze która jest wyciągnięta z gatewaya.

=== 2.6 Topic message

Informacje o tym jakie wartości z kamery zostały przekazane do wiadomości topica

== AWS Architecture Diagrams

[plantuml]
....
include::example$aws-1.puml[]
....

[plantuml]
....
include::example$aws-2.puml[]
....
