.TH "GCLOUD COMPUTE DISKS SNAPSHOT" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_disks_snapshot \- snapshot Google Compute Engine persistent disks
.SH "SYNOPSIS"
.HP
gcloud\ compute\ disks\ snapshot\ \fIDISK_NAME\fR [\fIDISK_NAME\fR\ \&...] [\fB\-\-description\fR\ \fIDESCRIPTION\fR] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-snapshot\-names\fR\ \fISNAPSHOT_NAME\fR [\fISNAPSHOT_NAME\fR\ \&...]] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-\-zone\fR\ \fIZONE\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute disks snapshot\fR creates snapshots of persistent disks\&. Snapshots are useful for backing up data or copying a persistent disk\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fIDISK_NAME\fR [\fIDISK_NAME\fR \&...]
.RS 4
The names of the disks to snapshot\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
An optional, textual description for the snapshots being created\&.
.RE
.PP
\fB\-\-snapshot\-names\fR \fISNAPSHOT_NAME\fR [\fISNAPSHOT_NAME\fR \&...]
.RS 4
Names to assign to the snapshots\&. Without this option, the name of each snapshot will be a random, 16\-character hexadecimal number that starts with a letter\&. The values of this option run parallel to the disks specified\&. For example,
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute disks snapshot my\-disk\-1 my\-disk\-2 my\-disk\-3 \e
    \-\-snapshot\-name snapshot\-1 snapshot\-2 snapshot\-3
.fi
.if n \{\
.RE
.\}
.sp
will result in
\fImy\-disk\-1\fR
being snapshotted as
\fIsnapshot\-1\fR,
\fImy\-disk\-2\fR
as
\fIsnapshot\-2\fR, and so on\&.
.RE
.PP
\fB\-\-zone\fR \fIZONE\fR
.RS 4
The zone of the disks to snapshot\&. If not specified, you will be prompted to select a zone\&.
.sp
To avoid prompting when this flag is omitted, you can set the
\fIcompute/zone\fR
property:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config set compute/zone ZONE
.fi
.if n \{\
.RE
.\}
.sp
A list of zones can fetched by running:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute zones list
.fi
.if n \{\
.RE
.\}
.sp
To unset the property, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config unset compute/zone
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, the zone can be stored in the environment variable
\fICLOUDSDK_COMPUTE_ZONE\fR\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
