.TH "GCLOUD COMPUTE BACKEND-SERVICES UPDATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_backend-services_update \- update a backend service
.SH "SYNOPSIS"
.HP
gcloud\ compute\ backend\-services\ update\ \fINAME\fR [\fB\-\-description\fR\ \fIDESCRIPTION\fR] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-http\-health\-checks\fR\ \fIHTTP_HEALTH_CHECK\fR [\fIHTTP_HEALTH_CHECK\fR\ \&...]] [\fB\-\-port\fR\ \fIPORT\fR] [\fB\-\-port\-name\fR\ \fIPORT_NAME\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-protocol\fR\ \fIPROTOCOL\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-timeout\fR\ \fITIMEOUT\fR] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute backend\-services update\fR is used to update backend services\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the backend service to update\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
An optional, textual description for the backend service\&.
.RE
.PP
\fB\-\-http\-health\-checks\fR \fIHTTP_HEALTH_CHECK\fR [\fIHTTP_HEALTH_CHECK\fR \&...]
.RS 4
Specifies a list of HTTP health check objects for checking the health of the backend service\&.
.RE
.PP
\fB\-\-port\fR \fIPORT\fR
.RS 4
The TCP port to use when connecting to the backend\&. \-\-port is being deprecated in favor of \-\-port\-name\&.
.RE
.PP
\fB\-\-port\-name\fR \fIPORT_NAME\fR
.RS 4
The name of a service that has been added to an instance group in this backend\&. Instance group services map a name to a port number which is used by the load balancing service\&. Only one
\fIport\-name\fR
may be added to a backend service, and that name must exist as a service on all instance groups that are a part of this backend service\&. The port number associated with the name may differ between instances\&. If you do not specify this flag, your instance groups must have a service named
\fIhttp\fR
configured\&. See
\fB*\fR\fBgcloud preview instance\-groups add\-service\fR(1)* for details\&.
.RE
.PP
\fB\-\-protocol\fR \fIPROTOCOL\fR
.RS 4
The protocol for incoming requests\&.
.RE
.PP
\fB\-\-timeout\fR \fITIMEOUT\fR
.RS 4
The amount of time to wait for a backend to respond to a request before considering the request failed\&. For example, specifying
\fI10s\fR
will give backends 10 seconds to respond to requests\&. Valid units for this flag are
\fIs\fR
for seconds,
\fIm\fR
for minutes, and
\fIh\fR
for hours\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
