.TH "GCLOUD COMPUTE FIREWALL-RULES CREATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_firewall-rules_create \- create a Google Compute Engine firewall rule
.SH "SYNOPSIS"
.HP
gcloud\ compute\ firewall\-rules\ create\ \fINAME\fR\ \fB\-\-allow\fR\ \fIPROTOCOL\fR[:_PORT_[\-\fIPORT\fR]] [\fIPROTOCOL\fR[:_PORT_[\-\fIPORT\fR]] \&...] [\fB\-\-description\fR\ \fIDESCRIPTION\fR] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-network\fR\ \fINETWORK\fR;\ default="default"] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-source\-ranges\fR\ \fICIDR_RANGE\fR [\fICIDR_RANGE\fR\ \&...]] [\fB\-\-source\-tags\fR\ \fITAG\fR [\fITAG\fR\ \&...]] [\fB\-\-target\-tags\fR\ \fITAG\fR [\fITAG\fR\ \&...]] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute firewall\-rules create\fR is used to create firewall rules to allow incoming traffic to a network\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the firewall rule to create\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-allow\fR \fIPROTOCOL\fR[:\fIPORT\fR[\-\fIPORT\fR]] [\fIPROTOCOL\fR[:\fIPORT\fR[\-\fIPORT\fR]] \&...]
.RS 4
A list of protocols and ports whose traffic will be allowed\&.
.sp
\fIPROTOCOL\fR
is the IP protocol whose traffic will be allowed\&.
\fIPROTOCOL\fR
can be either the name of a well\-known protocol (e\&.g\&.,
\fItcp\fR
or
\fIicmp\fR) or the IP protocol number\&. A list of IP protocols can be found at
http://www\&.iana\&.org/assignments/protocol\-numbers/protocol\-numbers\&.xhtml\&.
.sp
A port or port range can be specified after
\fIPROTOCOL\fR
to allow traffic through specific ports\&. If no port or port range is specified, connections through all ranges are allowed\&. For example, the following will create a rule that allows TCP traffic through port 80 and allows ICMP traffic:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute firewall\-rules create MY\-RULE \-\-allow tcp:80 icmp
.fi
.if n \{\
.RE
.\}
.sp
TCP and UDP rules must include a port or port range\&.
.RE
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
An optional, textual description for the firewall rule\&.
.RE
.PP
\fB\-\-network\fR \fINETWORK\fR; default="default"
.RS 4
The network to which this rule is attached\&. If omitted, the rule is attached to the
\fIdefault\fR
network\&.
.RE
.PP
\fB\-\-source\-ranges\fR \fICIDR_RANGE\fR [\fICIDR_RANGE\fR \&...]
.RS 4
A list of IP address blocks that are allowed to make inbound connections that match the firewall rule to the instances on the network\&. The IP address blocks must be specified in CIDR format:
http://en\&.wikipedia\&.org/wiki/Classless_Inter\-Domain_Routing\&. If neither \-\-source\-ranges nor \-\-source\-tags is provided, then this flag will default to
\fI0\&.0\&.0\&.0/0\fR, allowing all sources\&. Multiple IP address blocks can be specified if they are separated by spaces\&.
.RE
.PP
\fB\-\-source\-tags\fR \fITAG\fR [\fITAG\fR \&...]
.RS 4
A list of instance tags indicating the set of instances on the network which may accept inbound connections that match the firewall rule\&. If omitted, all instances on the network can receive inbound connections that match the rule\&.
.sp
Tags can be assigned to instances during instance creation\&.
.RE
.PP
\fB\-\-target\-tags\fR \fITAG\fR [\fITAG\fR \&...]
.RS 4
A list of instance tags indicating the set of instances on the network which may make network connections that match the firewall rule\&. If omitted, all instances on the network can make connections that match the rule\&.
.sp
Tags can be assigned to instances during instance creation\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
