.TH "GCLOUD COMPUTE BACKEND-SERVICES UPDATE-BACKEND" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_backend-services_update-backend \- update an existing backend in a backend service
.SH "SYNOPSIS"
.HP
gcloud\ compute\ backend\-services\ update\-backend\ \fINAME\fR [\fB\-\-balancing\-mode\fR\ \fIBALANCING_MODE\fR] [\fB\-\-capacity\-scaler\fR\ \fICAPACITY_SCALER\fR] [\fB\-\-description\fR\ \fIDESCRIPTION\fR] [\fB\-\-format\fR\ \fIFORMAT\fR] \fB\-\-group\fR\ \fIGROUP\fR [\fB\-\-help\fR] [\fB\-\-max\-rate\fR\ \fIMAX_RATE\fR\ | \ \fB\-\-max\-rate\-per\-instance\fR\ \fIMAX_RATE_PER_INSTANCE\fR] [\fB\-\-max\-utilization\fR\ \fIMAX_UTILIZATION\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-\-zone\fR\ \fIZONE\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute backend\-services update\-backend\fR updates a backend that is part of a backend service\&. This is useful for changing the way a backend behaves\&. Example changes that can be made include changing the load balancing policy and \fIdraining\fR a backend by setting its capacity scaler to zero\&.
.sp
\fIgcloud compute backend\-services edit\fR can also be used to update a backend if the use of a text editor is desired\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the backend service to update\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-balancing\-mode\fR \fIBALANCING_MODE\fR
.RS 4
Defines the strategy for balancing load\&.
\fIUTILIZATION\fR
will rely on the CPU utilization of the tasks in the group when balancing load\&. When using
\fIUTILIZATION\fR,
\fI\-\-max\-utilization\fR
can be used to set a maximum target CPU utilization for each task\&.
\fIRATE\fR
will spread load based on how many requests per second (RPS) the group can handle\&. There are two ways to specify max RPS:
\fI\-\-max\-rate\fR
which defines the max RPS for the whole group or
\fI\-\-max\-rate\-per\-task\fR
which defines the max RPS on a per\-task basis\&.
.sp
In
\fIUTILIZATION\fR, you can optionally limit based on RPS in addition to CPU by setting either
\fI\-\-max\-rate\-per\-task\fR
or
\fI\-\-max\-rate\fR\&.
.RE
.PP
\fB\-\-capacity\-scaler\fR \fICAPACITY_SCALER\fR
.RS 4
A float in the range [0\&.0, 1\&.0] that scales the maximum parameters for the group (e\&.g\&., max rate)\&. A value of 0\&.0 will cause no requests to be sent to the group (i\&.e\&., it adds the group in a
\fIdrained\fR
state)\&. The default is 1\&.0\&.
.RE
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
An optional, textual description for the backend\&.
.RE
.PP
\fB\-\-group\fR \fIGROUP\fR
.RS 4
The name or URI of a Google Cloud Resource View that can receive traffic\&.
.RE
.PP
\fB\-\-max\-rate\fR \fIMAX_RATE\fR
.RS 4
Maximum requests per second (RPS) that the group can handle\&.
.RE
.PP
\fB\-\-max\-rate\-per\-instance\fR \fIMAX_RATE_PER_INSTANCE\fR
.RS 4
The maximum per\-instance requests per second (RPS)\&.
.RE
.PP
\fB\-\-max\-utilization\fR \fIMAX_UTILIZATION\fR
.RS 4
The target CPU utilization for the group as a float in the range [0, 1e6]\&. This flag can only be provided when the balancing mode is
\fIUTILIZATION\fR\&.
.RE
.PP
\fB\-\-zone\fR \fIZONE\fR
.RS 4
The zone of the resource view to add to the backend service\&. If not specified, you will be prompted to select a zone\&.
.sp
To avoid prompting when this flag is omitted, you can set the
\fIcompute/zone\fR
property:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config set compute/zone ZONE
.fi
.if n \{\
.RE
.\}
.sp
A list of zones can fetched by running:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute zones list
.fi
.if n \{\
.RE
.\}
.sp
To unset the property, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config unset compute/zone
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, the zone can be stored in the environment variable
\fICLOUDSDK_COMPUTE_ZONE\fR\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
