.TH "GCLOUD COMPUTE ADDRESSES DELETE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_addresses_delete \- release reserved IP addresses
.SH "SYNOPSIS"
.HP
gcloud\ compute\ addresses\ delete\ \fINAME\fR [\fINAME\fR\ \&...] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-global\fR\ | \ \fB\-\-region\fR\ \fIREGION\fR] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute addresses delete\fR releases one or more Google Compute Engine IP addresses\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR [\fINAME\fR \&...]
.RS 4
The names of the addresses to delete\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-global\fR
.RS 4
If provided, it is assumed the addresses are global\&.
.RE
.PP
\fB\-\-region\fR \fIREGION\fR
.RS 4
The region of the address to operate on\&. If not specified, you will be prompted to select a region\&.
.sp
To avoid prompting when this flag is omitted, you can set the
\fIcompute/region\fR
property:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config set compute/region REGION
.fi
.if n \{\
.RE
.\}
.sp
A list of regions can fetched by running:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute regions list
.fi
.if n \{\
.RE
.\}
.sp
To unset the property, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config unset compute/region
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, the region can be stored in the environment variable
\fICLOUDSDK_COMPUTE_REGION\fR\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
