.TH "GCLOUD COMPUTE HTTP-HEALTH-CHECKS CREATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_http-health-checks_create \- create an HTTP health check to monitor load balanced instances
.SH "SYNOPSIS"
.HP
gcloud\ compute\ http\-health\-checks\ create\ \fINAME\fR [\fB\-\-check\-interval\fR\ \fICHECK_INTERVAL\fR;\ default="5s"] [\fB\-\-description\fR\ \fIDESCRIPTION\fR] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-healthy\-threshold\fR\ \fIHEALTHY_THRESHOLD\fR;\ default="2"] [\fB\-\-help\fR] [\fB\-\-host\fR\ \fIHOST\fR] [\fB\-\-port\fR\ \fIPORT\fR;\ default="80"] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-request\-path\fR\ \fIREQUEST_PATH\fR;\ default="/"] [\fB\-\-timeout\fR\ \fITIMEOUT\fR;\ default="5s"] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-\-unhealthy\-threshold\fR\ \fIUNHEALTHY_THRESHOLD\fR;\ default="2"] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute http\-health\-checks create\fR is used to create an HTTP health check\&. HTTP health checks monitor instances in a load balancer controlled by a target pool\&. All arguments to the command are optional except for the name of the health check\&. For more information on load balancing, see https://developers\&.google\&.com/compute/docs/load\-balancing/\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the HTTP health check\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-check\-interval\fR \fICHECK_INTERVAL\fR; default="5s"
.RS 4
How often to perform a health check for an instance\&. For example, specifying
\fI10s\fR
will run the check every 10 seconds\&. Valid units for this flag are
\fIs\fR
for seconds,
\fIm\fR
for minutes, and
\fIh\fR
for hours\&. The default value is
\fI5s\fR\&.
.RE
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
An optional, textual description for the HTTP health check\&.
.RE
.PP
\fB\-\-healthy\-threshold\fR \fIHEALTHY_THRESHOLD\fR; default="2"
.RS 4
The number of consecutive successful health checks before an unhealthy instance is marked as healthy\&. The default is 2\&.
.RE
.PP
\fB\-\-host\fR \fIHOST\fR
.RS 4
The value of the host header used in this HTTP health check request\&. By default, this is empty and Google Compute Engine automatically sets the host header in health requests to the same external IP address as the forwarding rule associated with the target pool\&.
.RE
.PP
\fB\-\-port\fR \fIPORT\fR; default="80"
.RS 4
The TCP port number that this health check monitors\&. The default value is 80\&.
.RE
.PP
\fB\-\-request\-path\fR \fIREQUEST_PATH\fR; default="/"
.RS 4
The request path that this health check monitors\&. For example,
\fI/healthcheck\fR\&. The default value is
\fI/\fR\&.
.RE
.PP
\fB\-\-timeout\fR \fITIMEOUT\fR; default="5s"
.RS 4
If Google Compute Engine doesn\(cqt receive an HTTP 200 response from the instance by the time specified by the value of this flag, the health check request is considered a failure\&. For example, specifying
\fI10s\fR
will cause the check to wait for 10 seconds before considering the request a failure\&. Valid units for this flag are
\fIs\fR
for seconds,
\fIm\fR
for minutes, and
\fIh\fR
for hours\&. The default value is
\fI5s\fR\&.
.RE
.PP
\fB\-\-unhealthy\-threshold\fR \fIUNHEALTHY_THRESHOLD\fR; default="2"
.RS 4
The number of consecutive health check failures before a healthy instance is marked as unhealthy\&. The default is 2\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
