.TH "GCLOUD COMPUTE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute \- read and manipulate Google Compute Engine resources
.SH "SYNOPSIS"
.HP
gcloud\ compute\ \fIGROUP\fR\ | \ \fICOMMAND\fR [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
Read and manipulate Google Compute Engine resources\&.
.SH "FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "GROUPS"
.sp
\fIGROUP\fR is one of the following:
.PP
\fBaddresses\fR
.RS 4
Read and manipulate Google Compute Engine addresses\&.
.RE
.PP
\fBbackend\-services\fR
.RS 4
List, create, and delete backend services\&.
.RE
.PP
\fBdisk\-types\fR
.RS 4
Read Google Compute Engine virtual disk types\&.
.RE
.PP
\fBdisks\fR
.RS 4
Read and manipulate Google Compute Engine disks\&.
.RE
.PP
\fBfirewall\-rules\fR
.RS 4
List, create, and delete Google Compute Engine firewall rules\&.
.RE
.PP
\fBforwarding\-rules\fR
.RS 4
Read and manipulate forwarding rules to send traffic to load balancers\&.
.RE
.PP
\fBhttp\-health\-checks\fR
.RS 4
Read and manipulate HTTP health checks for load balanced instances\&.
.RE
.PP
\fBimages\fR
.RS 4
List, create, and delete Google Compute Engine images\&.
.RE
.PP
\fBinstance\-groups\fR
.RS 4
Read and manipulate Google Compute Engine instance groups\&.
.RE
.PP
\fBinstance\-templates\fR
.RS 4
Read and manipulate Google Compute Engine instance templates\&.
.RE
.PP
\fBinstances\fR
.RS 4
Read and manipulate Google Compute Engine virtual machine instances\&.
.RE
.PP
\fBmachine\-types\fR
.RS 4
Read Google Compute Engine virtual machine types\&.
.RE
.PP
\fBnetworks\fR
.RS 4
List, create, and delete Google Compute Engine networks\&.
.RE
.PP
\fBoperations\fR
.RS 4
Read and manipulate Google Compute Engine operations\&.
.RE
.PP
\fBproject\-info\fR
.RS 4
Read and manipulate project\-level data like quotas and metadata\&.
.RE
.PP
\fBregions\fR
.RS 4
List Google Compute Engine regions\&.
.RE
.PP
\fBroutes\fR
.RS 4
Read and manipulate routes\&.
.RE
.PP
\fBsnapshots\fR
.RS 4
List, describe, and delete Google Compute Engine snapshots\&.
.RE
.PP
\fBtarget\-http\-proxies\fR
.RS 4
List, create, and delete target HTTP proxies\&.
.RE
.PP
\fBtarget\-instances\fR
.RS 4
Read and manipulate Google Compute Engine virtual target instances\&.
.RE
.PP
\fBtarget\-pools\fR
.RS 4
Read and manipulate Google Compute Engine target pools\&.
.RE
.PP
\fBurl\-maps\fR
.RS 4
List, create, and delete URL maps\&.
.RE
.PP
\fBzones\fR
.RS 4
List Google Compute Engine zones\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.PP
\fBconfig\-ssh\fR
.RS 4
Populate SSH config files with Host entries from each instance\&.
.RE
.PP
\fBcopy\-files\fR
.RS 4
Copy files to and from Google Compute Engine virtual machines\&.
.RE
.PP
\fBssh\fR
.RS 4
SSH into a virtual machine instance\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
