.TH "GCLOUD COMPUTE CONFIG-SSH" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_config-ssh \- populate SSH config files with Host entries from each instance
.SH "SYNOPSIS"
.HP
gcloud\ compute\ config\-ssh [\fB\-\-dry\-run\fR] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-remove\fR] [\fB\-\-ssh\-config\-file\fR\ \fISSH_CONFIG_FILE\fR] [\fB\-\-ssh\-key\-file\fR\ \fISSH_KEY_FILE\fR] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute config\-ssh\fR makes SSHing to virtual machine instances easier by adding an alias for each instance to the user SSH configuration (\fI~/\&.ssh/config\fR) file\&.
.sp
In most cases, it is sufficient to run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute config\-ssh
.fi
.if n \{\
.RE
.\}
.sp
Each instance will be given an alias of the form \fINAME\&.ZONE\&.PROJECT\fR\&. For example, if \fIexample\-instance\fR resides in \fIus\-central1\-a\fR, you can SSH to it by running:
.sp
.if n \{\
.RS 4
.\}
.nf
$ ssh example\-instance\&.us\-central1\-a\&.MY\-PROJECT
.fi
.if n \{\
.RE
.\}
.sp
On some platforms, the host alias can be tab\-completed, making the long alias less daunting to type\&.
.sp
The aliases created interface with SSH\-based programs like \fBscp(1)\fR, so it is possible to use the aliases elsewhere:
.sp
.if n \{\
.RS 4
.\}
.nf
$ scp ~/MY\-FILE example\-instance\&.us\-central1\-a\&.MY\-PROJECT:~
.fi
.if n \{\
.RE
.\}
.sp
Whenever instances are added, removed, or their external IP addresses are changed, this command should be re\-executed to update the configuration\&.
.SH "FLAGS"
.PP
\fB\-\-dry\-run\fR
.RS 4
If provided, the proposed changes to the SSH config file are printed to standard out and no actual changes are made\&.
.RE
.PP
\fB\-\-remove\fR
.RS 4
If provided, any changes made to the SSH config file by this tool are reverted\&.
.RE
.PP
\fB\-\-ssh\-config\-file\fR \fISSH_CONFIG_FILE\fR
.RS 4
Specifies an alternative per\-user SSH configuration file\&. By default, this is
\fI~/\&.ssh/config\fR\&.
.RE
.PP
\fB\-\-ssh\-key\-file\fR \fISSH_KEY_FILE\fR
.RS 4
The path to the SSH key file\&. By default, this is
\fI~/\&.ssh/google_compute_engine\fR\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
