.TH "GCLOUD COMPUTE REGIONS LIST" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_regions_list \- list Google Compute Engine regions
.SH "SYNOPSIS"
.HP
gcloud\ compute\ regions\ list [\fINAME\fR\ \&...] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-limit\fR\ \fILIMIT\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-regexp\fR\ \fIREGEXP\fR,\ \fB\-r\fR\ \fIREGEXP\fR] [\fB\-\-sort\-by\fR\ \fISORT_BY\fR] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-\-uri\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
List Google Compute Engine regions\&.
.SH "POSITIONAL ARGUMENTS"
.PP
[\fINAME\fR \&...]
.RS 4
If provided, show details for the specified names and/or URIs of resources\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-limit\fR \fILIMIT\fR
.RS 4
The maximum number of results\&.
.RE
.PP
\fB\-\-regexp\fR \fIREGEXP\fR, \fB\-r\fR \fIREGEXP\fR
.RS 4
A regular expression to filter the names of the results on\&. Any names that do not match the entire regular expression will be filtered out\&.
.RE
.PP
\fB\-\-sort\-by\fR \fISORT_BY\fR
.RS 4
A field to sort by\&. To perform a descending\-order sort, prefix the value of this flag with a tilde (\fI~\fR)\&.
.RE
.PP
\fB\-\-uri\fR
.RS 4
If provided, the list command will only print URIs for the resources returned\&. If this flag is not provided, the list command will print a human\-readable table of useful resource data\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
