.TH "GCLOUD COMPUTE ADDRESSES CREATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_addresses_create \- reserve IP addresses
.SH "SYNOPSIS"
.HP
gcloud\ compute\ addresses\ create [\fINAME\fR\ \&...] [\fB\-\-addresses\fR\ \fIADDRESS\fR [\fIADDRESS\fR\ \&...]] [\fB\-\-description\fR\ \fIDESCRIPTION\fR] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-global\fR\ | \ \fB\-\-region\fR\ \fIREGION\fR] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute addresses create\fR is used to reserve one or more IP addresses\&. Once an IP address is reserved, it will be associated with the project until it is released using \fIgcloud compute addresses delete\fR\&. Ephemeral IP addresses that are in use by resources in the project, can be reserved using the \fI\-\-addresses\fR flag\&.
.SH "POSITIONAL ARGUMENTS"
.PP
[\fINAME\fR \&...]
.RS 4
The names to assign to the reserved IP addresses\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-addresses\fR \fIADDRESS\fR [\fIADDRESS\fR \&...]
.RS 4
Ephemeral IP addresses to promote to reserved status\&. Only addresses that are being used by resources in the project can be promoted\&. When providing this flag, a parallel list of names for the addresses can be provided\&. For example,
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute addresses create ADDRESS\-1 ADDRESS\-2 \e
    \-\-addresses 162\&.222\&.181\&.197 162\&.222\&.181\&.198 \-\-region us\-central1
.fi
.if n \{\
.RE
.\}
.sp
will result in 162\&.222\&.181\&.197 being reserved as
\fIADDRESS\-1\fR
and 162\&.222\&.181\&.198 as
\fIADDRESS\-2\fR\&. If no names are given, randomly\-generated names will be assigned to the IP addresses\&.
.RE
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
An optional textual description for the addresses\&.
.RE
.PP
\fB\-\-global\fR
.RS 4
If provided, it is assumed the addresses are global\&.
.RE
.PP
\fB\-\-region\fR \fIREGION\fR
.RS 4
The region of the address to operate on\&. If not specified, you will be prompted to select a region\&.
.sp
To avoid prompting when this flag is omitted, you can set the
\fIcompute/region\fR
property:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config set compute/region REGION
.fi
.if n \{\
.RE
.\}
.sp
A list of regions can fetched by running:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute regions list
.fi
.if n \{\
.RE
.\}
.sp
To unset the property, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config unset compute/region
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, the region can be stored in the environment variable
\fICLOUDSDK_COMPUTE_REGION\fR\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "EXAMPLES"
.sp
To reserve three IP addresses in the \fIus\-central1\fR region, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute addresses create ADDRESS\-1 ADDRESS\-2 ADDRESS\-3 \e
    \-\-region us\-central1
.fi
.if n \{\
.RE
.\}
.sp
To reserve ephemeral IP addresses 162\&.222\&.181\&.198 and 23\&.251\&.146\&.189 which are being used by virtual machine instances in the \fIus\-central1\fR region, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute addresses create \-\-addresses 162\&.222\&.181\&.198 \e
    23\&.251\&.146\&.189 \-\-region us\-central1
.fi
.if n \{\
.RE
.\}
.sp
In the above invocation, the two addresses will be assigned random names\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
