.TH "GCLOUD COMPUTE URL-MAPS CREATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_url-maps_create \- create a URL map
.SH "SYNOPSIS"
.HP
gcloud\ compute\ url\-maps\ create\ \fINAME\fR\ \fB\-\-default\-service\fR\ \fIDEFAULT_SERVICE\fR [\fB\-\-description\fR\ \fIDESCRIPTION\fR] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute url\-maps create\fR is used to create URL maps which map HTTP and HTTPS request URLs to backend services\&. Mappings are done using a longest\-match strategy\&.
.sp
There are two components to a mapping: a host rule and a path matcher\&. A host rule maps one or more hosts to a path matcher\&. A path matcher maps request paths to backend services\&. For example, a host rule can map the hosts \fI*\&.google\&.com\fR and \fIgoogle\&.com\fR to a path matcher called \fIwww\fR\&. The \fIwww\fR path matcher in turn can map the path \fI/search/*\fR to the search backend service and everything else to a default backend service\&.
.sp
Host rules and patch matchers can be added to the URL map after the map is created by using \fIgcloud compute url\-maps edit\fR or by using \fIgcloud compute url\-maps add\-path\-matcher\fR and \fIgcloud compute url\-maps add\-host\-rule\fR\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the URL map\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-default\-service\fR \fIDEFAULT_SERVICE\fR
.RS 4
A backend service that will be used for requests for which this URL map has no mappings\&.
.RE
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
An optional, textual description for the URL map\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
