.TH "GCLOUD COMPUTE IMAGES DEPRECATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_images_deprecate \- manage deprecation status of Google Compute Engine images
.SH "SYNOPSIS"
.HP
gcloud\ compute\ images\ deprecate\ \fINAME\fR [\fB\-\-delete\-in\fR\ \fIDELETE_IN\fR\ | \ \fB\-\-delete\-on\fR\ \fIDELETE_ON\fR] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-obsolete\-in\fR\ \fIOBSOLETE_IN\fR\ | \ \fB\-\-obsolete\-on\fR\ \fIOBSOLETE_ON\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-replacement\fR\ \fIREPLACEMENT\fR] \fB\-\-state\fR\ \fISTATE\fR [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute images deprecate\fR is used to deprecate images\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the image to set deprecation status of\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-delete\-in\fR \fIDELETE_IN\fR
.RS 4
Specifies the amount of time until the image\(cqs status should be set to DELETED\&. For instance, specifying
\fI30d\fR
will set the status to DELETED in 30 days from the current system time\&. Valid units for this flag are
\fIs\fR
for seconds,
\fIm\fR
for minutes,
\fIh\fR
for hours and
\fId\fR
for days\&. If no unit is specified, seconds is assumed\&.
.sp
Note that the image will not be deleted automatically\&. The image will only be marked as deleted\&. An explicit request to delete the image must be made in order to remove it from the image list\&. This flag is mutually exclusive with \-\-delete\-on\&.
.RE
.PP
\fB\-\-delete\-on\fR \fIDELETE_ON\fR
.RS 4
Similar to \-\-delete\-in, but specifies an absolute time when the status should be set to DELETED\&. The date and time specified must be a valid RFC 3339 full\-date or date\-time\&. For times in UTC, this looks like
\fIYYYY\-MM\-DDTHH:MM:SSZ\fR\&. For example: 2020\-01\-02T00:00:00Z for midnight on January 2, 2020 in UTC\&. This flag is mutually exclusive with \-\-delete\-in\&.
.RE
.PP
\fB\-\-obsolete\-in\fR \fIOBSOLETE_IN\fR
.RS 4
Specifies time (in the same format as \-\-delete\-in) until this image\(cqs status should become OBSOLETE\&. Obsolete images will cause an error whenever an attempt is made to apply the image to a new disk\&. This flag is mutually exclusive with \-\-obsolete\-on\&.
.RE
.PP
\fB\-\-obsolete\-on\fR \fIOBSOLETE_ON\fR
.RS 4
Specifies time (in the same format as \-\-delete\-on) when this image\(cqs status should become OBSOLETE\&. This flag is mutually exclusive with \-\-obsolete\-in\&.
.RE
.PP
\fB\-\-replacement\fR \fIREPLACEMENT\fR
.RS 4
Specifies a Compute Engine image as a replacement for the image being phased out\&. Users of the deprecated image will be advised to switch to this replacement\&. For example,
_\-\-replacement example\-image_
or
_\-\-replacement projects/google/global/images/example\-image_\&. This flag is required when setting the image state to anything other than
\fIACTIVE\fR
or when \-\-delete\-in, \-\-delete\-on, \-\-obsolete\-in, or \-\-obsolete\-on is provided\&.
.RE
.PP
\fB\-\-state\fR \fISTATE\fR
.RS 4
The deprecation state to set on the image\&. An image\(cqs default state is
\fIACTIVE\fR, suggesting that the image is currently supported\&. Operations which create a new resource using a
\fIDEPRECATED\fR
image return successfully, but with a warning indicating that the image is deprecated and recommending its replacement\&. New uses of
\fIOBSOLETE\fR
or
\fIDELETED\fR
images result in an error\&. Note that setting the deprecation state to
\fIDELETED\fR
will not automatically delete the image\&. You must still make a request to delete the image to remove it from the image list\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "EXAMPLES"
.sp
To deprecate an image called \fIIMAGE\fR immediately, mark it as obsolete in one day, and mark it as deleted in two days, use:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute images deprecate IMAGE \-\-status DEPRECATED \e
    \-\-obsolete\-in 1d \-\-delete\-in 2d
.fi
.if n \{\
.RE
.\}
.sp
To un\-deprecate an image called \fIIMAGE\fR, use:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute images deprecate IMAGE \-\-status ACTIVE
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
