.TH "GCLOUD COMPUTE DISKS CREATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_disks_create \- create Google Compute Engine persistent disks
.SH "SYNOPSIS"
.HP
gcloud\ compute\ disks\ create\ \fINAME\fR [\fINAME\fR\ \&...] [\fB\-\-description\fR\ \fIDESCRIPTION\fR] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-image\fR\ \fIIMAGE\fR\ | \ \fB\-\-source\-snapshot\fR\ \fISOURCE_SNAPSHOT\fR] [\fB\-\-image\-project\fR\ \fIIMAGE_PROJECT\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-size\fR\ \fISIZE\fR] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-\-type\fR\ \fITYPE\fR] [\fB\-\-zone\fR\ \fIZONE\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute disks create\fR creates one or more Google Compute Engine persistent disks\&. When creating virtual machine instances, disks can be attached to the instances through the \fIgcloud compute instances create\fR command\&. Disks can also be attached to instances that are already running using \fIgloud compute instances attach\-disk\fR\&.
.sp
Disks are zonal resources, so they reside in a particular zone for their entire lifetime\&. The contents of a disk can be moved to a different zone by snapshotting the disk (using \fIgcloud compute disks snapshot\fR) and creating a new disk using \fI\-\-source\-snapshot\fR in the desired zone\&. The contents of a disk can also be moved across project or zone by creating an image (using \fIgcloud compute images create\fR) and creating a new disk using \fI\-\-image\fR in the desired project and/or zone\&.
.sp
When creating disks, be sure to include the \fI\-\-zone\fR option:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute disks create my\-disk\-1 my\-disk\-2 \-\-zone us\-east1\-a
.fi
.if n \{\
.RE
.\}
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR [\fINAME\fR \&...]
.RS 4
The names of the disks to create\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
An optional, textual description for the disks being created\&.
.RE
.PP
\fB\-\-image\fR \fIIMAGE\fR
.RS 4
An image to apply to the disks being created\&. When using this option, the size of the disks must be at least as large as the image size\&. Use
\fI\-\-size\fR
to adjust the size of the disks\&.
.sp
The value for this option can be the name of an image or an alias from the table below\&.
.TS
tab(:);
ltB ltB ltB.
T{
Alias
T}:T{
Project
T}:T{
Image Name
T}
.T&
lt lt lt
lt lt lt
lt lt lt
lt lt lt
lt lt lt
lt lt lt
lt lt lt
lt lt lt
lt lt lt
lt lt lt
lt lt lt
lt lt lt
lt lt lt
lt lt lt
lt lt lt.
T{
centos\-6
T}:T{
centos\-cloud
T}:T{
centos\-6
T}
T{
centos\-7
T}:T{
centos\-cloud
T}:T{
centos\-7
T}
T{
container\-vm
T}:T{
google\-containers
T}:T{
container\-vm
T}
T{
coreos
T}:T{
coreos\-cloud
T}:T{
coreos\-stable
T}
T{
debian\-7
T}:T{
debian\-cloud
T}:T{
debian\-7\-wheezy
T}
T{
debian\-7\-backports
T}:T{
debian\-cloud
T}:T{
backports\-debian\-7\-wheezy
T}
T{
opensuse\-13
T}:T{
opensuse\-cloud
T}:T{
opensuse\-13
T}
T{
rhel\-6
T}:T{
rhel\-cloud
T}:T{
rhel\-6
T}
T{
rhel\-7
T}:T{
rhel\-cloud
T}:T{
rhel\-7
T}
T{
sles\-11
T}:T{
suse\-cloud
T}:T{
sles\-11
T}
T{
sles\-12
T}:T{
suse\-cloud
T}:T{
sles\-12
T}
T{
ubuntu\-12\-04
T}:T{
ubuntu\-os\-cloud
T}:T{
ubuntu\-1204\-precise
T}
T{
ubuntu\-14\-04
T}:T{
ubuntu\-os\-cloud
T}:T{
ubuntu\-1404\-trusty
T}
T{
ubuntu\-14\-10
T}:T{
ubuntu\-os\-cloud
T}:T{
ubuntu\-1410\-utopic
T}
T{
windows\-2008\-r2
T}:T{
windows\-cloud
T}:T{
windows\-server\-2008\-r2
T}
.TE
.sp 1
When the value is an alias, this tool will query the public image project that contains the image type to find the latest image matching the alias\&. The user\(cqs project is also queried for an image with the same name as the alias\&. If a conflict exists, the user will be prompted to resolve the conflict\&.
.sp
To specify an image in another project for which there is no alias, use
\fI\-\-image\-project\fR\&. When
\fI\-\-image\-project\fR
is present, no API calls are made to resolve the image\&. This property is useful for scripts\&.
.sp
This flag is mutually exclusive with
\fI\-\-source\-snapshot\fR\&.
.RE
.PP
\fB\-\-image\-project\fR \fIIMAGE_PROJECT\fR
.RS 4
The project against which all image references will be resolved\&. See
\fI\-\-image\fR
for more details\&.
.RE
.PP
\fB\-\-size\fR \fISIZE\fR
.RS 4
Indicates the size of the disks\&. The value must be a whole number followed by a size unit of
\fIKB\fR
for kilobyte,
\fIMB\fR
for megabyte,
\fIGB\fR
for gigabyte, or
\fITB\fR
for terabyte\&. For example,
\fI10GB\fR
will produce 10 gigabyte disks\&. If omitted, a default size of 500 GB is used for standard disks and 200GB for SSD disks\&. The minimum size a disk can have is 1 GB\&. Disk size must be a multiple of 10 GB\&.
.RE
.PP
\fB\-\-source\-snapshot\fR \fISOURCE_SNAPSHOT\fR
.RS 4
A source snapshot used to create the disks\&. It is safe to delete a snapshot after a disk has been created from the snapshot\&. In such cases, the disks will no longer reference the deleted snapshot\&. To get a list of snapshots in your current project, run
gcloud compute snapshots list\&. A snapshot from an existing disk can be created using the
\fIgcloud compute disks snapshot\fR
command\&. This flag is mutually exclusive with
\fI\-\-image\fR\&.
.sp
When using this option, the size of the disks must be at least as large as the snapshot size\&. Use
\fI\-\-size\fR
to adjust the size of the disks\&.
.RE
.PP
\fB\-\-type\fR \fITYPE\fR
.RS 4
Specifies the type of disk to create\&. To get a list of available disk types, run
\fIgcloud compute disk\-types list\fR\&. The default disk type is pd\-standard\&.
.RE
.PP
\fB\-\-zone\fR \fIZONE\fR
.RS 4
The zone of the disks to create\&. If not specified, you will be prompted to select a zone\&.
.sp
To avoid prompting when this flag is omitted, you can set the
\fIcompute/zone\fR
property:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config set compute/zone ZONE
.fi
.if n \{\
.RE
.\}
.sp
A list of zones can fetched by running:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute zones list
.fi
.if n \{\
.RE
.\}
.sp
To unset the property, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config unset compute/zone
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, the zone can be stored in the environment variable
\fICLOUDSDK_COMPUTE_ZONE\fR\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
