.TH "GCLOUD COMPUTE BACKEND-SERVICES" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_backend-services \- list, create, and delete backend services
.SH "SYNOPSIS"
.HP
gcloud\ compute\ backend\-services\ \fICOMMAND\fR [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
List, create, and delete backend services\&.
.SH "FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.PP
\fBadd\-backend\fR
.RS 4
Add a backend to a backend service\&.
.RE
.PP
\fBcreate\fR
.RS 4
Create a backend service\&.
.RE
.PP
\fBdelete\fR
.RS 4
Delete backend services\&.
.RE
.PP
\fBdescribe\fR
.RS 4
Describe a backend service\&.
.RE
.PP
\fBedit\fR
.RS 4
Modify backend services\&.
.RE
.PP
\fBget\-health\fR
.RS 4
Get health status of backend(s) in an backend service\&.
.RE
.PP
\fBlist\fR
.RS 4
List backend services\&.
.RE
.PP
\fBremove\-backend\fR
.RS 4
Remove a backend frome a backend service\&.
.RE
.PP
\fBupdate\fR
.RS 4
Update a backend service\&.
.RE
.PP
\fBupdate\-backend\fR
.RS 4
Update an existing backend in a backend service\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
