.TH "GCLOUD COMPUTE FIREWALL-RULES UPDATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_firewall-rules_update \- update a firewall rule
.SH "SYNOPSIS"
.HP
gcloud\ compute\ firewall\-rules\ update\ \fINAME\fR [\fB\-\-allow\fR [\fIPROTOCOL\fR[:_PORT_[\-\fIPORT\fR]] \&...]] [\fB\-\-description\fR\ \fIDESCRIPTION\fR] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-source\-ranges\fR [\fICIDR_RANGE\fR\ \&...]] [\fB\-\-source\-tags\fR [\fITAG\fR\ \&...]] [\fB\-\-target\-tags\fR [\fITAG\fR\ \&...]] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute firewall\-rules update\fR is used to update firewall rules that allow incoming traffic to a network\&. Only arguments passed in will be updated on the firewall rule\&. Other attributes will remain unaffected\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the firewall rule to update\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-allow\fR [\fIPROTOCOL\fR[:\fIPORT\fR[\-\fIPORT\fR]] \&...]
.RS 4
A list of protocols and ports whose traffic will be allowed\&. Setting this will override the current values\&.
.sp
\fIPROTOCOL\fR
is the IP protocol whose traffic will be allowed\&.
\fIPROTOCOL\fR
can be either the name of a well\-known protocol (e\&.g\&.,
\fItcp\fR
or
\fIicmp\fR) or the IP protocol number\&. A list of IP protocols can be found at
http://www\&.iana\&.org/assignments/protocol\-numbers/protocol\-numbers\&.xhtml\&.
.sp
A port or port range can be specified after
\fIPROTOCOL\fR
to allow traffic through specific ports\&. If no port or port range is specified, connections through all ranges are allowed\&. For example, the following will create a rule that allows TCP traffic through port 80 and allows ICMP traffic:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute firewall\-rules update MY\-RULE \-\-allow tcp:80 icmp
.fi
.if n \{\
.RE
.\}
.sp
TCP and UDP rules must include a port or port range\&.
.RE
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
A textual description for the firewall rule\&. Set to an empty string to clear existing description\&.
.RE
.PP
\fB\-\-source\-ranges\fR [\fICIDR_RANGE\fR \&...]
.RS 4
A list of IP address blocks that are allowed to make inbound connections that match the firewall rule to the instances on the network\&. The IP address blocks must be specified in CIDR format:
http://en\&.wikipedia\&.org/wiki/Classless_Inter\-Domain_Routing\&. Setting this will override the existing source ranges for the firewall\&. The following will clear the existing source ranges:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute firewall\-rules update MY\-RULE \-\-source\-ranges
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fB\-\-source\-tags\fR [\fITAG\fR \&...]
.RS 4
A list of instance tags indicating the set of instances on the network which may accept inbound connections that match the firewall rule\&. If omitted, all instances on the network can receive inbound connections that match the rule\&.
.sp
Tags can be assigned to instances during instance creation\&. Setting this will override the existing source tags for the firewall\&. The following will clear the existing source tags:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute firewall\-rules update MY\-RULE \-\-source\-tags
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fB\-\-target\-tags\fR [\fITAG\fR \&...]
.RS 4
A list of instance tags indicating the set of instances on the network which may make network connections that match the firewall rule\&. If omitted, all instances on the network can make connections that match the rule\&.
.sp
Tags can be assigned to instances during instance creation\&. Setting this will override the existing target tags for the firewall\&. The following will clear the existing target tags:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute firewall\-rules update MY\-RULE \-\-target\-tags
.fi
.if n \{\
.RE
.\}
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
