.TH "GCLOUD AUTH" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_auth \- manage oauth2 credentials for the Google Cloud SDK
.SH "SYNOPSIS"
.HP
gcloud\ auth\ \fICOMMAND\fR [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
Manage oauth2 credentials for the Google Cloud SDK\&.
.SH "FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.PP
\fBactivate\-refresh\-token\fR
.RS 4
Get credentials via an existing refresh token\&.
.RE
.PP
\fBactivate\-service\-account\fR
.RS 4
Get credentials via the private key for a service account\&.
.RE
.PP
\fBlist\fR
.RS 4
List the accounts for known credentials\&.
.RE
.PP
\fBlogin\fR
.RS 4
Get credentials for the tools in the Google Cloud SDK via a web flow\&.
.RE
.PP
\fBrevoke\fR
.RS 4
Revoke authorization for credentials\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcore\fR component\&. See installing components if it is not installed\&.
