.TH "GCLOUD CONFIG SET" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_config_set \- edit Google Cloud SDK properties
.SH "SYNOPSIS"
.HP
gcloud\ config\ set\ \fISECTION\fR/\fIPROPERTY\fR\ \fIVALUE\fR [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT_ID\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-scope\fR\ \fISCOPE\fR] [\fB\-\-trace\-token\fR\ \fITRACE_TOKEN\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
Set the value for an option, so that Cloud SDK tools can use them as configuration\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fISECTION\fR/\fIPROPERTY\fR
.RS 4
The property to be set\&. Note that SECTION/ is optional while referring to properties in the core section\&.
.RE
.PP
\fIVALUE\fR
.RS 4
The value to be set\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-scope\fR \fISCOPE\fR
.RS 4
The scope flag determines which configuration file is modified by this operation\&. The files are read (and take precedence) in the following order:
.PP
\fBworkspace\fR
.RS 4
The workspace based configuration file is based on your current working directory\&. You can set project specific configuration here that will only take effect when working within that project\(cqs directory\&. You cannot set this value if you are not currently within a gcloud workspace\&. This will override all values from any other configuration files\&.
.RE
.PP
\fBuser\fR
.RS 4
The user based configuration file applies only to the current user of the system\&. It will override any values from the installation configuration\&.
.RE
.PP
\fBinstallation\fR
.RS 4
The installation based configuration file applies to all users on the system that use this version of the Cloud SDK\&. If the SDK was installed by an administrator, you will need administrator rights to make changes to this file\&.
.RE
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT_ID\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-\-trace\-token\fR \fITRACE_TOKEN\fR
.RS 4
Token used to route traces of service requests for investigation of issues\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "EXAMPLES"
.sp
To set the project property in the core section, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config set project myProject
.fi
.if n \{\
.RE
.\}
.sp
To set the zone property in the compute section, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config set compute/zone zone3
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcore\fR component\&. See installing components if it is not installed\&.
